### ISSUE TITLE
Incorrect figure numbers in README?

### ISSUE THREAD

**Issue by xgloom** [blockaid-project/artifact-eval#2]
I would like to evaluate this artifact, but I'm reading the following in `README.md`:

> Generates Figure 5, Table 2, and Figure 8 from the paper.

Table 2 makes a lot of sense, but Fig. 5 and 8 do not. The last figure in the paper is 3.

Could this be a mistake in the description? Thank you.

**Comment by zhangwen0411** [comment]
Thank you for pointing this out! The README referred to figure numbers in an earlier draft of the paper; I have updated it to match the final version of the paper.

**Comment by xgloom** [comment]
Awesome- thank you for fixing this so quickly. This is very clear and
helpful!

Op wo 28 feb 2024 om 18:56 schreef Wen Zhang ***@***.***>:

**Comment by xgloom** [comment]
Awesome- thank you for fixing this so quickly. This is very clear and
helpful!
